### ISSUE TITLE
Frontend checklist before deployment

### ISSUE THREAD

**Issue by jjcrab** [jjcrab/the-art-den#2]
- [ ] last minute troubleshooting
- [ ] update ReadMe
- [ ] Deploy to Heroku
- [ ] Add deploy link to GitHub about
- [ ] Add frontend link to backend ReadMe
